#!/bin/bash

# Generate a pre-signed URL from Telnyx Object Storage
# This allows temporary public access to your hold music file

echo "=== Telnyx Object Storage Pre-Signed URL Generator ==="
echo ""
echo "The direct URL (https://us-central-1.telnyxcloudstorage.com/hold-music/moonlightdrive.mp3)"
echo "returns 403 Forbidden because it requires authentication."
echo ""
echo "To get a pre-signed URL, you have two options:"
echo ""
echo "OPTION 1: Via Telnyx Portal (Easiest)"
echo "1. Go to: https://mission-control.telnyx.com"
echo "2. Navigate: Developer → Object Storage → hold-music folder"
echo "3. Right-click moonlightdrive.mp3 → Copy link (or Share button)"
echo "4. The URL will look like:"
echo "   https://telnyx-uploads.s3.amazonaws.com/obj_abc123xyz?Signature=...&Expires=..."
echo ""
echo "OPTION 2: Via API (if you have the object ID)"
echo "Export these variables:"
echo "  export TELNYX_API_KEY='your-api-key'"
echo "  export OBJECT_ID='obj_abc123xyz'  (get from portal)"
echo ""
echo "Then run:"
echo "  curl -X POST \"https://api.telnyx.com/v2/object_storage/objects/\$OBJECT_ID/signed_url\" \\"
echo "    -H \"Authorization: Bearer \$TELNYX_API_KEY\" \\"
echo "    -H \"Content-Type: application/json\" \\"
echo "    -d '{\"expires_in_seconds\": 604800}'"
echo ""
echo "This will return something like:"
echo "  {\"data\": {\"signed_url\": \"https://telnyx-uploads.s3.amazonaws.com/obj_abc123xyz?Signature=...&Expires=...\"}}"
echo ""
echo "Once you have the pre-signed URL:"
echo "1. Update Render environment: HOLD_MUSIC_URL=<your-presigned-url>"
echo "2. Test: curl -H 'Authorization: Bearer TOKEN' https://ai-agent-warrant.onrender.com/telnyx/hold_music_test"
echo ""
echo "The pre-signed URL will be valid for 7 days (604800 seconds)."
echo "After that, you'll need to generate a new one."
